// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package db

import (
	"context"
)

const healthcheck = `-- name: Healthcheck :one
SELECT now() AS current_time
`

func (q *Queries) Healthcheck(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, healthcheck)
	var current_time interface{}
	err := row.Scan(&current_time)
	return current_time, err
}
