// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID          pgtype.UUID        `json:"id"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	StoreID     pgtype.UUID        `json:"store_id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Action      string             `json:"action"`
	BeforeData  []byte             `json:"before_data"`
	AfterData   []byte             `json:"after_data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AuthUser struct {
	ID pgtype.UUID `json:"id"`
}

type AvailabilityEntry struct {
	ID               pgtype.UUID `json:"id"`
	SubmissionID     pgtype.UUID `json:"submission_id"`
	WorkDate         pgtype.Date `json:"work_date"`
	StartTime        pgtype.Time `json:"start_time"`
	EndTime          pgtype.Time `json:"end_time"`
	AvailabilityType string      `json:"availability_type"`
}

type AvailabilitySubmission struct {
	ID          pgtype.UUID        `json:"id"`
	PeriodID    pgtype.UUID        `json:"period_id"`
	StaffUserID pgtype.UUID        `json:"staff_user_id"`
	SubmittedBy pgtype.UUID        `json:"submitted_by"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ChangeRequest struct {
	ID              pgtype.UUID        `json:"id"`
	StoreID         pgtype.UUID        `json:"store_id"`
	PeriodID        pgtype.UUID        `json:"period_id"`
	AssignmentID    pgtype.UUID        `json:"assignment_id"`
	RequesterUserID pgtype.UUID        `json:"requester_user_id"`
	RequestType     string             `json:"request_type"`
	Reason          pgtype.Text        `json:"reason"`
	Status          string             `json:"status"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	DecisionNote    pgtype.Text        `json:"decision_note"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CoverageTarget struct {
	ID            pgtype.UUID `json:"id"`
	PeriodID      pgtype.UUID `json:"period_id"`
	DayOfWeek     int32       `json:"day_of_week"`
	StartTime     pgtype.Time `json:"start_time"`
	EndTime       pgtype.Time `json:"end_time"`
	RequiredCount int32       `json:"required_count"`
}

type Invite struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	UsedCount int32              `json:"used_count"`
	Status    string             `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Payload   []byte             `json:"payload"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchedulePeriod struct {
	ID                 pgtype.UUID        `json:"id"`
	StoreID            pgtype.UUID        `json:"store_id"`
	Name               string             `json:"name"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	SubmissionDeadline pgtype.Timestamptz `json:"submission_deadline"`
	Status             string             `json:"status"`
	PublishedAt        pgtype.Timestamptz `json:"published_at"`
	PublishedBy        pgtype.UUID        `json:"published_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ShiftAssignment struct {
	ID          pgtype.UUID        `json:"id"`
	PeriodID    pgtype.UUID        `json:"period_id"`
	StoreID     pgtype.UUID        `json:"store_id"`
	StaffUserID pgtype.UUID        `json:"staff_user_id"`
	WorkDate    pgtype.Date        `json:"work_date"`
	StartTime   pgtype.Time        `json:"start_time"`
	EndTime     pgtype.Time        `json:"end_time"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedBy   pgtype.UUID        `json:"updated_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Store struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type StoreMembership struct {
	ID         pgtype.UUID        `json:"id"`
	StoreID    pgtype.UUID        `json:"store_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Role       string             `json:"role"`
	Status     string             `json:"status"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
	DisabledAt pgtype.Timestamptz `json:"disabled_at"`
}
